# Generated by Django 4.0.5 on 2022-07-15 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from bossRaid.gen_master_data import gen_master


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BossRaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='보스 레이드 이름')),
                ('is_entered', models.BooleanField(default=True, verbose_name='입장 여부')),
            ],
            options={
                'verbose_name': '보스 레이드',
                'verbose_name_plural': '보스 레이드들',
                'db_table': 'db_boss_raid',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='BossRaidStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(verbose_name='레벨')),
                ('last_entertime', models.DateTimeField(auto_now_add=True, verbose_name='마지막 입장 시간')),
                ('boss_raid', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bossRaid.bossraid')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '보스 레이드 상태',
                'verbose_name_plural': '보스 레이드 상태들',
                'db_table': 'tb_boss_status',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='BossRaidHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(verbose_name='레벨')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='점수')),
                ('enter_time', models.DateTimeField(auto_now_add=True, verbose_name='입장 시간')),
                ('end_time', models.DateTimeField(auto_now=True, verbose_name='퇴장 시간')),
                ('boss_raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bossRaid.bossraid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '보스 레이드 기록',
                'verbose_name_plural': '보스 레이드 기록들',
                'db_table': 'tb_boss_history',
                'ordering': ('-id',),
            },
        ),
        migrations.RunPython(gen_master),
    ]
